version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_DB: larasns
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default

    environment:
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: larasns
      DB_USERNAME: default
      DB_PASSWORD: secret      
    #CircleCIでのテスト実施環境構築
    #CircleCIで実施するテストでは、あなたのPCのローカル環境で実施するテストとは違って、このように必要なパッケージを毎回インストールしなければならないということを覚えておいてください。
    steps:
      #githubからCircleCIの環境にソースコードをコピー（git clone）してくる。
      - checkout
      #composerのエラー回避処理
      - run: sudo composer self-update --1
      #保存されたキャッシュの復元(vendorディレクトリに情報が復元される)
      - restore_cache: 
          key: composer-v1-{{ checksum "composer.lock" }}

      #composerを使用してphp関連パッケージをインストール（checkoutの時点ではlaravelのフレームワークやPHPパッケージが存在しない）
      #同時にvendorディレクトリにキャッシュが作成される。
      - run: composer install -n --prefer-dist

      #keyにて指定した名前でキャッシュを保存(保存先はpathsで指定)
      - save_cache: 
          #ハッシュ値を算出しておくことで、composerに何か変更があれば、キャッシュを復元せずに新たなインストールを開始してそれをキャッシュとして保存してくれる。
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      #ここからはnpmのキャッシュ処理

      #
      - restore_cache: 
          key: npm-v1-{{ checksum "package-lock.json" }}

      - run:
          name: npm ci
          # | (パイプ)を一行目に書くことで、この後の処理が複数行あることを示す）
          #if文にて、node_modulesがなければtrueでnpm ciを走らせる
          #npmはインストール時にnode_modulesが削除されるので、もしnode_modulesがない時のみnpm ciを走らせるようにしている
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      #JavaScriptのトランスパイル
      - run: npm run dev
      - run: 
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql
            dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: 
          #CircleCIの画面の表示されるステップ名
          name: php test
          #実行するシェルコマンド
          command: ./vendor/bin/phpunit